# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20170225_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('originalAuthor', models.CharField(max_length=100)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotePublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('views', models.BigIntegerField()),
                ('upvotes', models.BigIntegerField()),
                ('text', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('originalAuthor', models.CharField(max_length=100)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotedata',
            name='author_ID',
        ),
        migrations.DeleteModel(
            name='QuoteData',
        ),
    ]
