# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artpublishcomment_quotepublishcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpublishcomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotepublishcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 8, 49, 20, 916000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
