# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170528_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(default=b'/static/images/dogeIsReal.jpeg', upload_to=b'/static/images'),
        ),
    ]
