# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170701_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(upload_to=b''),
        ),
    ]
